# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: install System
    init: |
      python -m pip install --upgrade pip
      pip install --upgrade robotframework
      pip install -r requirements.txt
      webdrivermanager firefox chrome --linkpath AUTO

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode@0.13.22
    - bierner.docs-view
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
